"""Add datetime

Revision ID: 1b83a8f4eac0
Revises: 0e85efb4392d
Create Date: 2021-07-30 13:36:06.072269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b83a8f4eac0'
down_revision = '0e85efb4392d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packets', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packets', 'timestamp')
    # ### end Alembic commands ###
