"""Add MultipartData Table

Revision ID: c4d9bd11b026
Revises: 2b7c069b10f5
Create Date: 2021-08-03 14:19:25.751992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d9bd11b026'
down_revision = '2b7c069b10f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multipart_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mp_packet_id', sa.Integer(), nullable=True),
    sa.Column('packet_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('idx', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mp_packet_id'], ['multipart_packets.id'], ),
    sa.ForeignKeyConstraint(['packet_id'], ['packets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('multipart_data')
    # ### end Alembic commands ###
