"""Add unique field

Revision ID: 1f04f413b8c8
Revises: faf643293e5d
Create Date: 2021-07-29 16:24:54.920045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f04f413b8c8'
down_revision = 'faf643293e5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'packets', ['packet'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'packets', type_='unique')
    # ### end Alembic commands ###
