"""Add back_populates

Revision ID: 2992403ff2f9
Revises: afaf16fa3aae
Create Date: 2021-08-09 12:44:16.359663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2992403ff2f9'
down_revision = 'afaf16fa3aae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
