"""Add back_populates to Packet

Revision ID: 3571f1f76f68
Revises: b4f4f523de0b
Create Date: 2021-08-09 15:19:13.543162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3571f1f76f68'
down_revision = 'b4f4f523de0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
