"""Remove back_populates to Packet

Revision ID: a82b1a98957c
Revises: 3571f1f76f68
Create Date: 2021-08-09 15:33:38.421209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a82b1a98957c'
down_revision = '3571f1f76f68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
