"""Add back_populates to MultipartPacket

Revision ID: b4f4f523de0b
Revises: 2992403ff2f9
Create Date: 2021-08-09 14:43:19.357787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4f4f523de0b'
down_revision = '2992403ff2f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
