"""Change field packet to type

Revision ID: d40a7025bcfa
Revises: a7172b7dd752
Create Date: 2021-08-03 13:04:40.202542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd40a7025bcfa'
down_revision = 'a7172b7dd752'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packets', sa.Column('type', sa.String(), nullable=True))
    op.drop_column('packets', 'packet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packets', sa.Column('packet', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('packets', 'type')
    # ### end Alembic commands ###
