"""Refactoe

Revision ID: 054deffe4e20
Revises: a709340b1e6e
Create Date: 2021-08-03 14:50:20.421544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '054deffe4e20'
down_revision = 'a709340b1e6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
