"""Add MultipartPacket Table

Revision ID: 2b7c069b10f5
Revises: d8864e4eb31c
Create Date: 2021-08-03 14:04:14.683886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b7c069b10f5'
down_revision = 'd8864e4eb31c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multipart_packets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_packet_id', sa.Integer(), nullable=True),
    sa.Column('end_packet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['end_packet_id'], ['packets.id'], ),
    sa.ForeignKeyConstraint(['start_packet_id'], ['packets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('multipart_packets')
    # ### end Alembic commands ###
