"""Refactor

Revision ID: 5beeacf7415c
Revises: 800782c07e16
Create Date: 2021-08-03 15:01:12.970777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5beeacf7415c'
down_revision = '800782c07e16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
