"""Refactor

Revision ID: 800782c07e16
Revises: f2ab2133a536
Create Date: 2021-08-03 14:55:27.260228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800782c07e16'
down_revision = 'f2ab2133a536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
