"""Add Relation to Packet

Revision ID: a709340b1e6e
Revises: c4d9bd11b026
Create Date: 2021-08-03 14:47:10.481463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a709340b1e6e'
down_revision = 'c4d9bd11b026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
