"""Add client_id field

Revision ID: a7172b7dd752
Revises: 1b83a8f4eac0
Create Date: 2021-07-30 16:20:24.001519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7172b7dd752'
down_revision = '1b83a8f4eac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packets', sa.Column('client_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packets', 'client_id')
    # ### end Alembic commands ###
