"""Change client_id field

Revision ID: afaf16fa3aae
Revises: a47c92e61a19
Create Date: 2021-08-04 16:05:28.011476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afaf16fa3aae'
down_revision = 'a47c92e61a19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
