"""Refactor

Revision ID: ce535c46bb01
Revises: 5beeacf7415c
Create Date: 2021-08-03 15:07:29.849676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce535c46bb01'
down_revision = '5beeacf7415c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
