"""Add DataPacket Table

Revision ID: d8864e4eb31c
Revises: d40a7025bcfa
Create Date: 2021-08-03 13:12:02.617662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8864e4eb31c'
down_revision = 'd40a7025bcfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_packets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('packet_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['packet_id'], ['packets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_packets')
    # ### end Alembic commands ###
