"""Refactor

Revision ID: e9a3d686b04d
Revises: 054deffe4e20
Create Date: 2021-08-03 14:51:28.014812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9a3d686b04d'
down_revision = '054deffe4e20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
