"""Refactor

Revision ID: f2ab2133a536
Revises: e9a3d686b04d
Create Date: 2021-08-03 14:52:20.703350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2ab2133a536'
down_revision = 'e9a3d686b04d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
